# Generated by Django 5.0.1 on 2024-01-27 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('company_name', models.CharField(max_length=50)),
                ('register_date', models.DateTimeField(default=datetime.datetime(2024, 1, 27, 16, 53, 14, 985178))),
            ],
        ),
    ]
