services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    #volumes:
    #  - .:/app
    environment:
      DEBUG: "true"
    env_file:
      - .env
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && chmod +x /app/entrypoint.sh && /app/entrypoint.sh"
    #volumes:
    #  - staticfiles:/app/staticfiles
    depends_on:
      - db
      
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: my_db
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  #staticfiles:
  #  external: true
  postgres_data: